/* The sequence of triangle numbers is generated by adding the natural numbers. So the 7th triangle number would be 1 + 2 + 3 + 4 + 5 + 6 + 7 = 28. The first ten terms would be:

1, 3, 6, 10, 15, 21, 28, 36, 45, 55, ...

Let us list the factors of the first seven triangle numbers:

 1: 1
 3: 1,3
 6: 1,2,3,6
10: 1,2,5,10
15: 1,3,5,15
21: 1,3,7,21
28: 1,2,4,7,14,28
We can see that 28 is the first triangle number to have over five divisors.

What is the value of the first triangle number to have over five hundred divisors?
*/

    let triangleNumbers = [0];

    let d = 100000000;

    for (let i = 1; i <= d; i++) {
        triangleNumbers.push(triangleNumbers[i - 1] + i);
    }
    console.log(triangleNumbers);

// console.log(triangleNumber(1));
// console.log(triangleNumber(2));
// console.log(triangleNumber(4));
// console.log(triangleNumber(6));
// console.log(triangleNumber(7));

function triangleDivisor() {
for (let i = 1; i <= d; i++) {
    let divisors = [];
    for (let j = 1; j <= triangleNumbers[i]; j++) {
        if (triangleNumbers[i] % j === 0) {
            divisors.push(j);
        }
        }
        if (divisors.length > 500) {
            return triangleNumbers[i];
        }
}
}
console.log(triangleDivisor());